version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/src
    volumes:
      - ./src:/var/src